Repository kenyihq/project-aeroalarm-silabuz, pull requests merged in 2023-02, with the labels that each got.

#4 Eliminando carpeta
  auth-rtk-jwt/.gitignore
  auth-rtk-jwt/README.md
  auth-rtk-jwt/package-lock.json
  auth-rtk-jwt/package.json
  auth-rtk-jwt/public/favicon.ico
  auth-rtk-jwt/public/index.html
  auth-rtk-jwt/public/logo192.png
  auth-rtk-jwt/public/logo512.png
  auth-rtk-jwt/public/manifest.json
  auth-rtk-jwt/public/robots.txt
  auth-rtk-jwt/src/App.css
  auth-rtk-jwt/src/App.test.tsx
  auth-rtk-jwt/src/App.tsx
  auth-rtk-jwt/src/app/hooks.ts
  auth-rtk-jwt/src/app/store.ts
  auth-rtk-jwt/src/features/counter/Counter.module.css
  auth-rtk-jwt/src/features/counter/Counter.tsx
  auth-rtk-jwt/src/features/counter/counterAPI.ts
  auth-rtk-jwt/src/features/counter/counterSlice.spec.ts
  auth-rtk-jwt/src/features/counter/counterSlice.ts
  auth-rtk-jwt/src/index.css
  auth-rtk-jwt/src/index.tsx
  auth-rtk-jwt/src/logo.svg
  auth-rtk-jwt/src/react-app-env.d.ts
  auth-rtk-jwt/src/reportWebVitals.ts
  auth-rtk-jwt/src/setupTests.ts
  auth-rtk-jwt/tsconfig.json
Labels: bug, duplicate

#6 Fernando/branch
  src/App.css
  src/App.tsx
  src/Assets/icon/logo.png
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/navbar.css
  src/components/Navbar/navbar.css.map
  src/components/Navbar/navbar.scss
  src/components/login/login.tsx
  src/components/pages/Login.tsx
  src/components/routing.tsx
Labels: enhancement

#7 Desplazando login
  src/components/login/login.tsx
  src/index.css
Labels: good first issue

#8 Fernando/branch
  src/App.css
  src/App.tsx
  src/Assets/mia.jpg
  src/Assets/miami.png
  src/components/Filtrado/Filtrado.tsx
  src/components/Filtrado/filtrado.css
  src/components/Filtrado/filtrado.css.map
  src/components/Filtrado/filtrado.scss
  src/components/Footer/Footer.tsx
  src/components/Footer/footer.css
  src/components/Footer/footer.css.map
  src/components/Footer/footer.scss
  src/components/Home/Home.tsx
  src/components/Home/home.css
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/navbar.css.map
  src/components/Navbar/navbar.scss
  src/components/Promo/Promo.tsx
  src/components/Promo/promo.css
  src/components/Promo/promo.css.map
  src/components/Promo/promo.scss
  src/components/pages/Filtrado.tsx
  src/components/pages/Footer.tsx
  src/components/pages/Promo.tsx
  src/components/routing.tsx
Labels: enhancement

#11 Feature: add register/login with supabase
  package-lock.json
  package.json
  src/components/login/login.tsx
Labels: enhancement
